// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_ProductCta from "./islands/AddToCartButton/ProductCta.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BuyTogether from "./islands/BuyTogether.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $LoginHeader from "./islands/LoginHeader.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $Popup from "./islands/Popup.tsx";
import * as $PrincipalImages from "./islands/PrincipalImages.tsx";
import * as $ProductCardInfo from "./islands/ProductCardInfo.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SelectableBanners from "./islands/SelectableBanners.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SimilarsGrid from "./islands/SimilarsGrid.tsx";
import * as $SkuSelector from "./islands/SkuSelector.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/ProductCta.tsx": $AddToCartButton_ProductCta,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BuyTogether.tsx": $BuyTogether,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/LoginHeader.tsx": $LoginHeader,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/Popup.tsx": $Popup,
    "./islands/PrincipalImages.tsx": $PrincipalImages,
    "./islands/ProductCardInfo.tsx": $ProductCardInfo,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SelectableBanners.tsx": $SelectableBanners,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SimilarsGrid.tsx": $SimilarsGrid,
    "./islands/SkuSelector.tsx": $SkuSelector,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
