// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addToCart.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$$$$0 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$2 from "./sections/Content/AvaliationSection.tsx";
import * as $$$$$$3 from "./sections/Content/Benefits.tsx";
import * as $$$$$$4 from "./sections/Content/Faq.tsx";
import * as $$$$$$5 from "./sections/Content/ImageAndText.tsx";
import * as $$$$$$6 from "./sections/Content/InfoSection.tsx";
import * as $$$$$$8 from "./sections/Content/Logos.tsx";
import * as $$$$$$7 from "./sections/Content/LPCategoryCards.tsx";
import * as $$$$$$9 from "./sections/Content/PagesSection.tsx";
import * as $$$$$$10 from "./sections/Content/PurchaseByCategory.tsx";
import * as $$$$$$11 from "./sections/Content/ReviewCarousel.tsx";
import * as $$$$$$12 from "./sections/Content/SectionDescription.tsx";
import * as $$$$$$13 from "./sections/Content/SpecificDetails.tsx";
import * as $$$$$$14 from "./sections/Content/SuggestionBanners.tsx";
import * as $$$$$$15 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$16 from "./sections/Footer/Footer.tsx";
import * as $$$$$$17 from "./sections/Header/Header.tsx";
import * as $$$$$$18 from "./sections/Images/BannerCategories.tsx";
import * as $$$$$$19 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$20 from "./sections/Images/Carousel.tsx";
import * as $$$$$$21 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$22 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$23 from "./sections/Institutional/InstitutionalSection.tsx";
import * as $$$$$$24 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$25 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$26 from "./sections/Miscellaneous/CampaignHero.tsx";
import * as $$$$$$27 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$28 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$29 from "./sections/Miscellaneous/Mailbiz.tsx";
import * as $$$$$$30 from "./sections/Miscellaneous/Popup.tsx";
import * as $$$$$$31 from "./sections/Miscellaneous/Widde.tsx";
import * as $$$$$$32 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$33 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$34 from "./sections/Product/ProductMatch.tsx";
import * as $$$$$$35 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$36 from "./sections/Product/ProductShelfBlack.tsx";
import * as $$$$$$37 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$38 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$39 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$40 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$41 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/cristaistavares/loaders/Layouts/ProductCard.tsx": $$$0,
  },
  "sections": {
    "deco-sites/cristaistavares/sections/Category/CategoryBanner.tsx": $$$$$$0,
    "deco-sites/cristaistavares/sections/Category/CategoryList.tsx": $$$$$$1,
    "deco-sites/cristaistavares/sections/Content/AvaliationSection.tsx":
      $$$$$$2,
    "deco-sites/cristaistavares/sections/Content/Benefits.tsx": $$$$$$3,
    "deco-sites/cristaistavares/sections/Content/Faq.tsx": $$$$$$4,
    "deco-sites/cristaistavares/sections/Content/ImageAndText.tsx": $$$$$$5,
    "deco-sites/cristaistavares/sections/Content/InfoSection.tsx": $$$$$$6,
    "deco-sites/cristaistavares/sections/Content/Logos.tsx": $$$$$$8,
    "deco-sites/cristaistavares/sections/Content/LPCategoryCards.tsx": $$$$$$7,
    "deco-sites/cristaistavares/sections/Content/PagesSection.tsx": $$$$$$9,
    "deco-sites/cristaistavares/sections/Content/PurchaseByCategory.tsx":
      $$$$$$10,
    "deco-sites/cristaistavares/sections/Content/ReviewCarousel.tsx": $$$$$$11,
    "deco-sites/cristaistavares/sections/Content/SectionDescription.tsx":
      $$$$$$12,
    "deco-sites/cristaistavares/sections/Content/SpecificDetails.tsx": $$$$$$13,
    "deco-sites/cristaistavares/sections/Content/SuggestionBanners.tsx":
      $$$$$$14,
    "deco-sites/cristaistavares/sections/Content/Testimonials.tsx": $$$$$$15,
    "deco-sites/cristaistavares/sections/Footer/Footer.tsx": $$$$$$16,
    "deco-sites/cristaistavares/sections/Header/Header.tsx": $$$$$$17,
    "deco-sites/cristaistavares/sections/Images/BannerCategories.tsx": $$$$$$18,
    "deco-sites/cristaistavares/sections/Images/BannerGrid.tsx": $$$$$$19,
    "deco-sites/cristaistavares/sections/Images/Carousel.tsx": $$$$$$20,
    "deco-sites/cristaistavares/sections/Images/ImageGallery.tsx": $$$$$$21,
    "deco-sites/cristaistavares/sections/Images/ShoppableBanner.tsx": $$$$$$22,
    "deco-sites/cristaistavares/sections/Institutional/InstitutionalSection.tsx":
      $$$$$$23,
    "deco-sites/cristaistavares/sections/Links/LinkTree.tsx": $$$$$$24,
    "deco-sites/cristaistavares/sections/Links/Shortcuts.tsx": $$$$$$25,
    "deco-sites/cristaistavares/sections/Miscellaneous/CampaignHero.tsx":
      $$$$$$26,
    "deco-sites/cristaistavares/sections/Miscellaneous/CampaignTimer.tsx":
      $$$$$$27,
    "deco-sites/cristaistavares/sections/Miscellaneous/CookieConsent.tsx":
      $$$$$$28,
    "deco-sites/cristaistavares/sections/Miscellaneous/Mailbiz.tsx": $$$$$$29,
    "deco-sites/cristaistavares/sections/Miscellaneous/Popup.tsx": $$$$$$30,
    "deco-sites/cristaistavares/sections/Miscellaneous/Widde.tsx": $$$$$$31,
    "deco-sites/cristaistavares/sections/Newsletter/Newsletter.tsx": $$$$$$32,
    "deco-sites/cristaistavares/sections/Product/ProductDetails.tsx": $$$$$$33,
    "deco-sites/cristaistavares/sections/Product/ProductMatch.tsx": $$$$$$34,
    "deco-sites/cristaistavares/sections/Product/ProductShelf.tsx": $$$$$$35,
    "deco-sites/cristaistavares/sections/Product/ProductShelfBlack.tsx":
      $$$$$$36,
    "deco-sites/cristaistavares/sections/Product/SearchResult.tsx": $$$$$$37,
    "deco-sites/cristaistavares/sections/Product/Wishlist.tsx": $$$$$$38,
    "deco-sites/cristaistavares/sections/Social/InstagramPosts.tsx": $$$$$$39,
    "deco-sites/cristaistavares/sections/Social/WhatsApp.tsx": $$$$$$40,
    "deco-sites/cristaistavares/sections/Theme/Theme.tsx": $$$$$$41,
  },
  "actions": {
    "deco-sites/cristaistavares/actions/addToCart.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/cristaistavares/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/cristaistavares/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/cristaistavares",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
